# Generated by Django 4.2.4 on 2024-01-25 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=255)),
                ('Author', models.CharField(max_length=255)),
                ('Content', models.TextField(null=True)),
                ('img', models.ImageField(upload_to='article_img/')),
                ('author_img', models.ImageField(upload_to='author_img/')),
                ('rating', models.DecimalField(decimal_places=2, max_digits=8)),
                ('PublishDate', models.DateField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255, null=True)),
                ('img', models.ImageField(upload_to='banner_img/')),
            ],
        ),
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('img', models.ImageField(upload_to='brand_img/')),
            ],
        ),
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=255)),
                ('Email', models.CharField(max_length=255, null=True)),
                ('Subject', models.CharField(max_length=255, null=True)),
                ('Message', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Subscribers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Email', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(upload_to='home_video/')),
            ],
        ),
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('home_img', models.ImageField(upload_to='home_img/')),
                ('price', models.IntegerField()),
                ('user_img', models.ImageField(upload_to='user_img/')),
                ('user_name', models.CharField(max_length=255)),
                ('user_location', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('popular', 'popular'), ('new house', 'new house'), ('best deals', 'best deals')], max_length=50)),
                ('bathrooms', models.IntegerField()),
                ('bedrooms', models.IntegerField()),
                ('carports', models.IntegerField()),
                ('floors', models.IntegerField()),
                ('descriptions', models.CharField(max_length=255)),
                ('created_at', models.DateField()),
                ('video', models.ManyToManyField(to='main.video')),
            ],
        ),
    ]
