# Generated by Django 4.2.4 on 2024-02-07 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='created_at',
            field=models.DateTimeField(),
        ),
    ]
